INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measure (description) VALUES ('teaspoon');
INSERT INTO unit_of_measure (description) VALUES ('tablespoon');
INSERT INTO unit_of_measure (description) VALUES ('tablespoons');
INSERT INTO unit_of_measure (description) VALUES ('cup');
INSERT INTO unit_of_measure (description) VALUES ('pinch');
INSERT INTO unit_of_measure (description) VALUES ('ounce');
INSERT INTO unit_of_measure (description) VALUES ('ounces');